version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=your-openai-api-key

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./frontend:/app
